name: Deploy
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out repository code
                uses: actions/checkout@v4
            -
                name: Install dependencies
                run: npm i
            -
                name: Builds Server code
                run: npm run build-server
            -
                name: Builds Client code
                run: npm run build-client
            -
                name: copy Server files via ssh key
                uses: garygrossgarten/github-action-scp@release
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    port: ${{ secrets.PORT }}
                    privateKey: ${{ secrets.KEY }}
                    passphrase: ${{ secrets.PASSPHRASE }}
                    local: server
                    remote: /var/www/electronics/server/
            -
                name: copy Client file via ssh key
                uses: garygrossgarten/github-action-scp@release
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    port: ${{ secrets.PORT }}
                    privateKey: ${{ secrets.KEY }}
                    passphrase: ${{ secrets.PASSPHRASE }}
                    local: client
                    remote: /var/www/electronics/client/